version: 0.0
os: linux
files:
  - source: /
    destination: /sweet-skills-api
hooks:
  BeforeInstall:
    - location: codeDeploy/scripts/BeforeInstall
      timeout: 300
      runas: root
  AfterInstall:
    - location: codeDeploy/scripts/AfterInstall
      timout: 300
      runas: root
  ApplicationStart:
    - location: codeDeploy/scripts/ApplicationStart
      timeout: 300
      runas: root
  ApplicationStop:
    - location: codeDeploy/scripts/ApplicationStop
      timeout: 300
      runas: root

